---
language: erlang
otp_release:
- 17.5
- 18.3
- 19.2
install:
- "./_test/bootstrap.sh"
script:
- configlet .
- "./_test/check-exercises.escript"
cache:
  - apt
  - directories:
    - $HOME/bin

sudo: false
