---
language: erlang
otp_release:
- 18.3
- 19.3
- 20.0
install:
- "./_test/bootstrap.sh"
script:
- configlet lint .
- pushd testgen; rebar3 escriptize; popd # TODO: before merging into master, try to do this in a separate env via buildmatrix
# - "./_test/check-exercises.escript"
- "./bin/journey-test.sh"
cache:
  - apt
  - cache bundler
  - directories:
    - $HOME/bin

sudo: false
