name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["20.3", "21.3", "22.0"]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v1
    - name: run tests
      run: |
        apt update && apt install --yes jq
        ./bin/journey-test.sh
