name: Check UUID validity

on: [push]

jobs:
  uuid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install --yes jq
    - run: |
        bad_uuid=$(cat config.json | jq --raw-output '.exercises | map(.uuid) | .[]' | grep -vE '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
        if [[ -n "$bad_uuid" ]]; then
          printf "Invalid UUID(s) found:"
          printf "%s" "${bad_uuid}"
          exit 1
        fi